worker_processes 1;

error_log /dev/stderr warn;
events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;

    log_format upstream_log '$remote_addr - $remote_user [$time_local] "$request" '
                                '$status $body_bytes_sent "$http_referer" '
                                '"$http_user_agent" upstream_addr=$upstream_addr '
                                'upstream_status=$upstream_status '
                                'upstream_response_time=$upstream_response_time';
    
    access_log /dev/stdout upstream_log;


    # Список серверов, куда будут проксироваться запросы.
    # Подробности по ссылке:
    # https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/
    upstream backend {
        # Метод балансировки: round-robin (по умолчанию)
        # Другие методы: least_conn, ip_hash
        server valuator-1:5001;
        server valuator-2:5002;
    }

    # 8080 порт - точка входа для пользователей
    server {
        listen 8080;
        server_name localhost;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
