services:
  redis:
    image: redis:alpine
    container_name: valuator
    ports:
      - 6379:6379# Используем официальный образ .NET SDK для сборки
  FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
  WORKDIR /src
  
  # Копируем файл проекта и восстанавливаем зависимости
  COPY Valuator/Valuator.csproj Valuator/
  RUN dotnet restore "Valuator/Valuator.csproj"
  
  # Копируем остальные файлы и собираем приложение
  COPY Valuator/ Valuator/
  WORKDIR /src/Valuator
  RUN dotnet build "Valuator.csproj" -c Release -o /app/build
  
  # Публикуем приложение
  FROM build AS publish
  RUN dotnet publish "Valuator.csproj" -c Release -o /app/publish
  
  # Используем runtime образ для запуска
  FROM mcr.microsoft.com/dotnet/aspnet:10.0-chiseled AS final
  WORKDIR /app
  COPY --from=publish /app/publish .
  
  # Изменяем строку подключения к Redis на имя сервиса в Docker
  ENV ConnectionStrings__Redis="redis:6379"
  
  ENTRYPOINT ["dotnet", "Valuator.dll"]
